spring.application.name=ProductCatelogService


#https://spring.io/guides/gs/accessing-data-mysql     -> to get all the properties for mysql
# H2 Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/productcatelogservice
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password


# JPA Configuration
# following configuration is used to create the table automatically in the database if it is not present.
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
#To show the query which is running in the console.
spring.jpa.show-sql=true

